### ISSUE TITLE
Problem with network IPv4 address carry-over

### ISSUE THREAD

**Issue by noskcajn** [pyouroboros/ouroboros#193] opened 2019-02-07 15:04 UTC
Thank you for the watchtower alternative!

I have a container that has a statically set IPv4 address, 192.168.110.189, and uses a custom network, pub_net (using the macvlan driver).

When the image is updated for the container the IPv4 address does not carry over.

JSON snippet before update:

"Networks":{"pub_net":{"IPAMConfig":{"IPv4Address":"192.168.110.189"},
"Links":null,
"Aliases":["3cae90f8d084"],
"NetworkID":"5e9c23c1a6132f507d2233e866aa2d49cae21f2579fb7e0d9feab354483d2aca",
"EndpointID":"a7ca96c18fe54a0991099bf2cc55b63c50d1515aefe3bf0a1001130d7f0f77d0",
"Gateway":"192.168.110.1",
"IPAddress":"192.168.110.189",
"IPPrefixLen":24,
"IPv6Gateway":"",
"GlobalIPv6Address":"",
"GlobalIPv6PrefixLen":0,
"MacAddress":"02:02:02:a8:6e:bd",
"DriverOpts":null,
"IPAMOperational":false}},

After:
"Networks":{"pub_net":{"IPAMConfig":null,
"Links":null,
"Aliases":["d0272f83f199"],
"NetworkID":"5e9c23c1a6132f507d2233e866aa2d49cae21f2579fb7e0d9feab354483d2aca",
"EndpointID":"c9b0d6e89241340be094ee8786d21a82257cbfc342d80f00373a87270e2a1a38",
"Gateway":"192.168.110.1",
"IPAddress":"192.168.110.2",
"IPPrefixLen":24,
"IPv6Gateway":"",
"GlobalIPv6Address":"",
"GlobalIPv6PrefixLen":0,
"MacAddress":"02:02:02:a8:6e:02",
"DriverOpts":null,
"IPAMOperational":false}},

The main difference appears to be the IPAMConfig information does not carry over, and then doesn't reflect in IPAddress.

**Comment by DirtyCajunRice** [comment] 2019-02-07 15:27
well thats less than ideal. I dont have statically assigned IPs so i never caught that! Ill dig into the code today and see why the structure is ignoring it. 

Out of curiosity, what is your use case for static in docker? (Havent had any glaring reasons myself yet)

**Comment by noskcajn** [comment] 2019-02-07 15:48
Plex and pihole are a couple.

**Comment by DirtyCajunRice** [comment] 2019-02-07 16:22
Ah. so personal preference. ( I dont need static for those). I will update in a bit when i have a change to dig in.

**Comment by noskcajn** [comment] 2019-02-07 17:51
So, yes, personal preference. Thanks again for looking into it.

**Comment by cotillion** [comment] 2019-02-08 08:25
This is also a problem for network aliases (such as created by docker-compose)

I suspect set_properties in helpers.py needs to be updated to handle networking

**Comment by frebib** [comment] 2019-02-09 12:08
+1 my updated containers are not resolvable on in the network which just straight-up breaks connectivity :(

**Comment by nightvisi0n** [comment] 2019-02-09 12:23
I also have kind of the same problem. I have some containers that are attached to more than one network, after the update they are no longer connected to the second network.

After having a short look at the code, this (and the issue of @noskcajn) might be due currently ouroboros does not carry over any networking config at all (correct me if I'm wrong): [ouroboros/pyouroboros/helpers.py](https://github.com/pyouroboros/ouroboros/blob/master/pyouroboros/helpers.py)

**Comment by nightvisi0n** [comment] 2019-02-09 13:14
I just tried to reproduce this issue:  

```shell
docker network create test --subnet=10.13.37.0/24 --gateway=10.13.37.1
docker run -d --name=test --network=test --ip=10.13.37.2 fedora:28 sleep 999999
docker inspect test > /tmp/before
docker run -it --rm --name=ouroboros --hostname=ouroboros -v /var/run/docker.sock:/var/run/docker.sock pyouroboros/ouroboros --run-once --latest
docker inspect test > /tmp/after
diff -u /tmp/before /tmp/after
```

And here is the diff between before the ouroboros run and after (I stripped not relevant lines):

```diff
--- /tmp/before 2019-02-09 14:07:15.910396995 +0100
+++ /tmp/after  2019-02-09 14:07:46.925436479 +0100
@@ -133,8 +133,8 @@
             "Domainname": "",
             "User": "",
             "AttachStdin": false,
-            "AttachStdout": false,
-            "AttachStderr": false,
+            "AttachStdout": true,
+            "AttachStderr": true,
             "Tty": false,
             "OpenStdin": false,
             "StdinOnce": false,
@@ -177,15 +177,13 @@
             "MacAddress": "",
             "Networks": {
                 "test": {
-                    "IPAMConfig": {
-                        "IPv4Address": "10.13.37.2"
-                    },
+                    "IPAMConfig": null,
                     "Links": null,
                     "Aliases": [
                         "f0b013fcc760"
                     ],
                     "NetworkID": "717de8744adee3253bb915dff0ba0dd6997351d8bf56ffd3ea81f710161fdbf3",
                     "EndpointID": "f94821ae24454b46378e8f2b6fbe060baad1884362aea761eaa118fdd7b53778",
                     "Gateway": "10.13.37.1",
                     "IPAddress": "10.13.37.2",
                     "IPPrefixLen": 24,
```

This diff reveals the issue of @noskcajn (and also possible another bug regarding `AttachStdout` and `AttachStderr`).

**Comment by nightvisi0n** [comment] 2019-02-09 13:23
And here is a diff when updating a container with multiple networks attached (again I stripped non relevant lines, including the `AttachStderr/out` thing):

```diff
--- /tmp/before 2019-02-09 14:19:51.312223134 +0100
+++ /tmp/after  2019-02-09 14:20:19.046256642 +0100
@@ -159,46 +159,31 @@
         },
         "NetworkSettings": {
             "Bridge": "",
             "SandboxID": "fae8f68bb085bcd6b11c7e5410e0f269912eca3b8dbafadc1d7f329e6087540f",
             "HairpinMode": false,
             "LinkLocalIPv6Address": "",
             "LinkLocalIPv6PrefixLen": 0,
             "Ports": {},
             "SandboxKey": "/var/run/docker/netns/fae8f68bb085",
             "SecondaryIPAddresses": null,
             "SecondaryIPv6Addresses": null,
              "EndpointID": "",
-            "Gateway": "192.168.169.1",
-            "GlobalIPv6Address": "fd4c:5f97:84be:b89e:0:242:c0a8:a902",
-            "GlobalIPv6PrefixLen": 64,
-            "IPAddress": "192.168.169.2",
-            "IPPrefixLen": 24,
-            "IPv6Gateway": "fd4c:5f97:84be:b89e::1",
-            "MacAddress": "02:42:c0:a8:a9:02",
+            "Gateway": "",
+            "GlobalIPv6Address": "",
+            "GlobalIPv6PrefixLen": 0,
+            "IPAddress": "",
+            "IPPrefixLen": 0,
+            "IPv6Gateway": "",
+            "MacAddress": "",
             "Networks": {
-                "bridge": {
-                    "IPAMConfig": {},
-                    "Links": null,
-                    "Aliases": [],
-                    "NetworkID": "dff833bfdf56f2f3926a61564ea94f09df0afe4a8b157a51188d978be063f9f8",
-                    "EndpointID": "2b7669211dafb598725fa21bb37cda8eb3e1104cfb37bd4ba050baf6baa3590d",
-                    "Gateway": "192.168.169.1",
-                    "IPAddress": "192.168.169.2",
-                    "IPPrefixLen": 24,
-                    "IPv6Gateway": "fd4c:5f97:84be:b89e::1",
-                    "GlobalIPv6Address": "fd4c:5f97:84be:b89e:0:242:c0a8:a902",
-                    "GlobalIPv6PrefixLen": 64,
-                    "MacAddress": "02:42:c0:a8:a9:02",
-                    "DriverOpts": null
-                },
                 "test": {
                     "IPAMConfig": null,
                     "Links": null,
                     "Aliases": [
                         "e8dc1e1e01d8"
                     ],
                     "NetworkID": "717de8744adee3253bb915dff0ba0dd6997351d8bf56ffd3ea81f710161fdbf3",
                     "EndpointID": "2c36dbcbcbe8b956bec809cb0e43633b8d5c137c629b9378512e7836cf538779",
                     "Gateway": "10.13.37.1",
                     "IPAddress": "10.13.37.2",
                     "IPPrefixLen": 24,

```

Apparently only one network is carried over (`test`), but both should be.

**Comment by nightvisi0n** [comment] 2019-02-09 15:49
@noskcajn I implemented a fix in #195. If you would like to test if that fixes your issue you can build an updated image with the following command:  
```shell
docker build -t ouroboros:local-build https://github.com/pyouroboros/ouroboros.git#pull/195/head

**Comment by circa10a** [comment] 2019-02-10 15:42
This can be tested using our `-develop` tag now.

**Comment by cotillion** [comment] 2019-02-11 09:38
Appears to work!
The new container gets both the new and old containers hostname as alias however, but I dont' think that'll cause any issues.


```
                   "Aliases": [
                        "xxxxxx",
                        "99598a0c9ce6",
                        "1acdbc70ee05"
                    ],
```

**Comment by nightvisi0n** [comment] 2019-02-11 12:36
That's intended, because otherwise we would need to classify labels and decide for each one whether to carry it over or not.. As these IDs are sha256 hashes a collision should be very unlikely.

**Comment by DirtyCajunRice** [comment] 2019-02-11 15:27
@nightvisi0n did you get a chance to push the bugfix for the last push with ipv6?

**Comment by nightvisi0n** [comment] 2019-02-11 16:17
@DirtyCajunRice I wait for @frebib to verify that it's fixing his issue.. but I can also create a PR right now if you want

**Comment by DirtyCajunRice** [comment] 2019-02-11 16:18
@nightvisi0n Yeah make the pr so it can be commented on and adjusted if needed :)

**Comment by nightvisi0n** [comment] 2019-02-11 16:42
There it is: #200

**Comment by frebib** [comment] 2019-02-11 16:49
@nightvisi0n I've not hand chance yet. Hopefully I'll get time tonight when I get home from work.
At the moment, #197 is more of a breaking issue right now

**Comment by frebib** [comment] 2019-02-11 16:51
@nightvisi0n As for removing the old hostname from the label-set, it would probably be a good idea to at the very least, add an opt-in option to remove the old hostname from the labels just so that list doesn't grow over time.

**Comment by DirtyCajunRice** [comment] 2019-02-11 16:53
they _ARE_ just sha. The numerical chances of it being an issue are quite small. I dont know if the list growing is even a real concern. It is a thought. Just dont know if it has any concerning weight

**Comment by noskcajn** [comment] 2019-02-11 17:27
Initial testing using the develop tag appears to keep IP information as expected. I will try further testing as I can. So far it looks good.

**Comment by DirtyCajunRice** [comment] 2019-02-12 00:30
Ok. This is working in develop going to close this one out.

**Closed by DirtyCajunRice** 2019-02-12 00:30 UTC
Labels: bug
