### ISSUE TITLE
ouroboros sets fixed IP addresses

### ISSUE THREAD

**Issue by fabianonline** [pyouroboros/ouroboros#254] opened 2019-03-07 11:03 UTC
Hi.

After rebooting my server, I've noticed that some containers were in a state of "Stopped (255)" and couldn't be restarted anymore. Trying to do so yielded an `Error response from daemon: Address already in use`. Recreating them did work, but I would rather like them to be automatically restarted after a reboot like all the other containers.

After some thinking about this I think I found the problem: ouroboros sets fixed IP adresses on containers it restarts. These persist even after a reboot of the server. But all containers that were not touched by ouroboros still don't have a fixed IP and will dynamically grep the first available one - which can happen to be one attached to a not-yet-running-but-about-to-be-started container. This will of course prevent that container from starting...

I did a `docker inspect` of a container after creating it and again after ouroboros updated it. A diff yielded (amongst other things like changed Id and Created values):

```diff
             "Networks": {
                 "ldap": {
-                    "IPAMConfig": {},
+                    "IPAMConfig": {
+                        "IPv4Address": "172.22.0.4"
+                    },
                     "Links": null,
                     "Aliases": [
-                        "1b32d47d1fef"
+                        "1b32d47d1fef",
+                        "2745cfe3c1c0"
                     ],
...
                 "mariadb": {
-                    "IPAMConfig": null,
+                    "IPAMConfig": {
+                        "IPv4Address": "172.18.0.2"
+                    },
                     "Links": null,
                     "Aliases": [
-                        "1b32d47d1fef"
+                        "1b32d47d1fef",
+                        "2745cfe3c1c0"
                     ],
...
                 "nginx": {
-                    "IPAMConfig": {},
+                    "IPAMConfig": {
+                        "IPv4Address": "172.19.0.12"
+                    },
                     "Links": null,
                     "Aliases": [
-                        "1b32d47d1fef"
+                        "1b32d47d1fef",
+                        "2745cfe3c1c0"
                     ],
```

I think this matches my hypothesis.

Expected behaviour would be that ouroboros doesn't set a fixed IP if there isn't a fixed IP to begin with.

**Comment by circa10a** [comment] 2019-03-09 19:27
This is by design:
https://github.com/pyouroboros/ouroboros/blob/master/pyouroboros/dockerclient.py#L153

We've seen several issues with keeping network configs for things that dynamically provision docker networks like docker-compose and I dont think there's a way to determine if the ip address was manually set or not.

**Comment by ginkel** [comment] 2019-03-09 20:12
Hm, watchtower does not exhibit this behavior. Whether that's a missing feature or intentional, I don't know. As is, ouroboros is pretty unusable for me as many containers break after reboot due to address collisions. If the address status of a container (explicit address assignment vs. automatic allocation) cannot be inferred, what about adding a label to identify containers with an explicitly allocated address? I'd expect these to be a minority.

**Comment by fabianonline** [comment] 2019-03-09 20:16
I just did a small test:
```sh
$ docker run -d --name test --net nginx nginx ; sleep 10; docker inspect test > without_ip ; docker rm -f test
$ docker run -d --name test --net nginx --ip 172.22.0.200 nginx ; sleep 10; docker inspect test > with_ip ; docker rm -f test
$ diff -u without_ip with_ip
```

This diff contains:

```diff
         "NetworkSettings": {
...
             "Networks": {
                 "nginx": {
-                    "IPAMConfig": null,
+                    "IPAMConfig": {
+                        "IPv4Address": "172.22.0.200"
+                    },
```

I don't know about docker-compose and friends, but at least running a container "manually" (which is what I'm doing most of the time), the `IPAMConfig: null` seems to indicate a dynamically set IP, while a fixed IP would be indicated by something like `IPAMConfig: { IPv4Address: <IP>}`.

**Comment by circa10a** [comment] 2019-03-09 20:35
Ah, so we can probably do a check like so:

pseudocode:

```python

**Comment by DirtyCajunRice** [comment] 2019-03-09 22:04
how exactly is there address collisions. all its doing is reusing the ip address it used before. that makes no sense

**Comment by fabianonline** [comment] 2019-03-09 23:07
Just ouroboros restarting a container isn't the problem. But restarting docker or even the server can lead to problem:

Assume you have a container, let's just say nginx. Of the four containers in it's network, nginx was started second. So it dynamically got the IP address 172.22.0.2. An update for the nginx image leads to ouroboros pulling it ans recreating nginx, setting the IP to be statically set to 172.22.0.2.
Later, the server gets rebooted. This time, the order in which the containers were started after boot is different - container_a is first and dynamically gets 172.22.0.1, container_b dynamically gets 172.22.0.2. Then it's nginx' turn - which can't be started because 172.22.0.2 is already being used...

**Comment by DirtyCajunRice** [comment] 2019-03-11 00:21
@fabianonline after further reading through this while i had more time... you are in a very odd place. The code is written in such a way to only allow this in a circumstance that you have manually defined the network. 
Correct me if i am wrong, but you are attaching these containers to a network that you have explicitly defined and created outside of compose with a subnet and a gateway... and then are dhcp'ing the containers correct?

If the above is true... why?

**Comment by ginkel** [comment] 2019-03-11 08:49
I'm not using docker-compose to deploy the Docker containers and networks, but Ansible, which creates the networks before attaching containers to them (via DHCP).

So, at least for me, this is a pretty standard scenario.

**Comment by fabianonline** [comment] 2019-03-12 10:34
I have some containers running which need access to other containers. For example one single nginx container acting as reverse proxy for all other containers doing web stuff. Or an LDAP server providing the necessary data to be able to log into different services.

I was using the `link` feature of docker, but since that is deprecated for some time now, I switched over to using custom networks to allow inter-container-communication. https://docs.docker.com/network/links/

I'm not doing anything extremely fancy - basically just `docker network create ldap` followed by `docker network connect ldap <container>`. I don't care about which IP settings are set where and just use the IPs docker's managing.

**Comment by DirtyCajunRice** [comment] 2019-03-25 01:36
Pushed the example above code. should be in develop tonight. let me know how it goes with testing people

**Comment by LckyLuciano** [comment] 2019-04-04 15:50
I am also experiencing this issue.  I replaced Watchtower with Ouroboros this week and it has updated a total of 3 containers.  2 of those were created with Ansible, and those same 2 containers will not start after a host reboot.  I get the "Error response from daemon: Address already in use" when trying to start them.

**Comment by DirtyCajunRice** [comment] 2019-04-04 16:53
@LckyLuciano is that with master or develop

**Comment by LckyLuciano** [comment] 2019-04-04 17:27
Master, I believe.  I'm using the docker image:  pyouroboros/ouroboros:latest

**Comment by DirtyCajunRice** [comment] 2019-04-04 18:21
no one confirmed that dev fix worked. if you can confirm its fixed in dev ill push to master tonight

**Comment by LckyLuciano** [comment] 2019-04-04 23:40
Thanks. I switched over to the develop build.  No container updates today, but I'll follow up when I get one and restart the host.

**Comment by mammo0** [comment] 2019-04-07 09:27
@DirtyCajunRice I've tested the current develop image from dockerhub.

**And I can confirm that the fix works.** My other docker containers were updated correctly and no fixed IP was set on the newly created containers. A restart of the docker service or a whole server reboot works without any problems now.

Thanks, @circa10a

**Comment by LckyLuciano** [comment] 2019-04-07 22:00
I can also confirm that this is working in the develop image.  Thank you.

**Comment by DirtyCajunRice** [comment] 2019-04-09 02:31
Awesome. Closing and will merge soon.

**Closed by DirtyCajunRice** 2019-04-09 02:31 UTC
Labels: bug
