### ISSUE TITLE
[Feature Request] Support for Swarm Services

### ISSUE THREAD

**Issue by computeralex92** [pyouroboros/ouroboros#178] opened 2019-02-02 19:20 UTC
It would be great if Ouroboros detect and update services deployed in a Docker Swarm cluster.
A support for swarm services is already in dockerpy: 
https://docker-py.readthedocs.io/en/stable/services.html

**Comment by DirtyCajunRice** [comment] 2019-02-07 02:37
@computeralex92 added in develop. Please take a few moments to test it out and ensure it works as intended. Currently it only works with labels with the mentality of "If you can use swarm, you can use labels"

**Comment by computeralex92** [comment] 2019-02-07 09:18
While the dry mode is working without any issue, the update of a service is failing:

```
python3 ./ouroboros -o -S
2019-02-07 10:16:16 : INFO : ouroboros : Version: 1.2.0-develop
2019-02-07 10:16:16 : INFO : base : Scheduler started
2019-02-07 10:16:16 : INFO : base : Added job "Run Once container update for ********unix://********.sock" to job store "default"
2019-02-07 10:16:16 : INFO : base : Running job "Run Once container update for unix://var/run/docker.sock (trigger: date[2019-02-07 10:16:16 CET], next run at: 2019-02-07 10:16:16 CET)" (scheduled at 2019-02-07 10:16:16.457317+01:00)
2019-02-07 10:16:16 : INFO : base : Removed job 4d22e7bc754644738f6fd59d60080a06
2019-02-07 10:16:18 : INFO : dockerclient : mirror_nginx will be updated
2019-02-07 10:16:18 : ERROR : base : Job "Run Once container update for unix://var/run/docker.sock (trigger: date[2019-02-07 10:16:16 CET], next run at: 2019-02-07 10:16:16 CET)" raised an exception
Traceback (most recent call last):
  File "/root/ouroboros/virtualenv/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/ouroboros/application/pyouroboros/dockerclient.py", line 406, in update
    self.notification_manager.send(container_tuples=updated_service_tuples, socket=self.socket, kind='update')
  File "/root/ouroboros/application/pyouroboros/notifiers.py", line 57, in send
    ) for container, old_image, new_image in container_tuples
  File "/root/ouroboros/application/pyouroboros/notifiers.py", line 57, in <listcomp>
    ) for container, old_image, new_image in container_tuples
AttributeError: 'str' object has no attribute 'short_id'
2019-02-07 10:16:18 : INFO : base : Scheduler has been shut down
```

**Comment by DirtyCajunRice** [comment] 2019-02-07 15:28
So good and bad news. that is not the service, but the notifier that is erroring. Can you confirm the service did not update as well?

**Comment by computeralex92** [comment] 2019-02-07 15:38
It seems that the update itself was working; the container in the service is used for testing were recreated.

Btw:
I get now this error when I run it in dry mode:
```2019-02-07 16:36:12 : ERROR : base : Job "Run Once container update for unix://var/run/docker.sock (trigger: date[2019-02-07 16:36:12 CET], next run at: 2019-02-07 16:36:12 CET)" raised an exception
Traceback (most recent call last):
  File "/root/ouroboros/virtualenv/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/ouroboros/application/pyouroboros/dockerclient.py", line 369, in update
    sha256 = image_string.split('@')[1][7:]
IndexError: list index out of range```

**Comment by DirtyCajunRice** [comment] 2019-02-12 00:25
the above fixes the notification error. I am going to need the output of image_string to know whats going on there. can you add a `print(image_string)` on the next line (370) in dockerclient.py and give me the output?

**Comment by computeralex92** [comment] 2019-02-12 07:34
I added the print in both branches of the code; the result is in both cases the same:

```
2019-02-12 08:33:39 : INFO : ouroboros : Version: 1.2.0-develop
nginx:stable-alpine
2019-02-12 08:33:39 : ERROR : base : Job "Run Once container update for unix://var/run/docker.sock (trigger: date[2019-02-12 08:33:39 CET], next run at: 2019-02-12 08:33:39 CET)" raised an exception
Traceback (most recent call last):
  File "/root/ouroboros/virtualenv/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/ouroboros/application/pyouroboros/dockerclient.py", line 426, in update
    sha256 = image_string.split('@')[1][7:]
IndexError: list index out of range
```

**Comment by DirtyCajunRice** [comment] 2019-02-12 07:42
lots of updates since i posted that. looks like line 425 needs the print now. (basically the line above the error line)

**Comment by computeralex92** [comment] 2019-02-12 07:45
OK, i added the line; the code part here is:

```
         for service in self.monitored:
             image_string = service.attrs['Spec']['TaskTemplate']['ContainerSpec']['Image']
             print(image_string)
             tag = image_string.split('@')[0]
             print(image_string)
             sha256 = image_string.split('@')[1][7:]
```

The error message is:

```
# python3 ./ouroboros -A -o -S
2019-02-12 08:45:19 : INFO : ouroboros : Version: 1.2.0-develop
nginx:stable-alpine
nginx:stable-alpine
2019-02-12 08:45:19 : ERROR : base : Job "Run Once container update for unix://var/run/docker.sock (trigger: date[2019-02-12 08:45:19 CET], next run at: 2019-02-12 08:45:19 CET)" raised an exception
Traceback (most recent call last):
  File "/root/ouroboros/virtualenv/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/ouroboros/application/pyouroboros/dockerclient.py", line 425, in update
    sha256 = image_string.split('@')[1][7:]
IndexError: list index out of range
```

**Comment by DirtyCajunRice** [comment] 2019-02-12 15:55
interesting... its totally missing the sha. I appreciate you working with me (I cant seem to replicate it myself so this helps). Can you put another print in that shows all the attrs?
```
         for service in self.monitored:
             print(service.attrs)
             image_string = service.attrs['Spec']['TaskTemplate']['ContainerSpec']['Image']
             print(image_string)
             tag = image_string.split('@')[0]
             print(image_string)
             sha256 = image_string.split('@')[1][7:]
```

**Comment by computeralex92** [comment] 2019-02-13 16:22
Here is the output:

```2019-02-13 17:19:43 : INFO : ouroboros : Version: 1.2.0-develop
{'ID': 'v3q5os7qywevqvk6km1ml44rk', 'Version': {'Index': 2466}, 'CreatedAt': '2019-01-15T12:40:15.681790818Z', 'UpdatedAt': '2019-02-12T07:27:08.750889355Z', 'Spec': {'Name': 'mirror_nginx', 'Labels': {'com.docker.stack.image': 'nginx:stable-alpine', 'com.docker.stack.namespace': 'mirror', 'com.ouroboros.enable': 'true', 'traefik.backend': 'Mirror', 'traefik.docker.network': 'mirror', 'traefik.enable': 'true', 'traefik.frontend': 'Mirror', 'traefik.frontend.rule': 'Host:HOST', 'traefik.port': '80'}, 'TaskTemplate': {'ContainerSpec': {'Image': 'nginx:stable-alpine', 'Labels': {'com.docker.stack.namespace': 'mirror'}, 'Privileges': {'CredentialSpec': None, 'SELinuxContext': None}, 'Mounts': [{'Type': 'bind', 'Source': '/opt/docker/mirror/nginx/nginx.conf', 'Target': '/etc/nginx/nginx.conf', 'ReadOnly': True}, {'Type': 'bind', 'Source': '/opt/mirror/', 'Target': '/var/www/vhosts/mirror', 'ReadOnly': True}], 'StopGracePeriod': 10000000000, 'DNSConfig': {}, 'Isolation': 'default'}, 'Resources': {}, 'RestartPolicy': {'Condition': 'any', 'Delay': 5000000000, 'MaxAttempts': 0}, 'Placement': {'Platforms': [{'Architecture': 'amd64', 'OS': 'linux'}, {'OS': 'linux'}, {'Architecture': 'arm64', 'OS': 'linux'}, {'Architecture': '386', 'OS': 'linux'}, {'Architecture': 'ppc64le', 'OS': 'linux'}, {'Architecture': 's390x', 'OS': 'linux'}]}, 'Networks': [{'Target': 'j8ma50vt0chbvwjf3fvwfw6t7', 'Aliases': ['nginx']}], 'ForceUpdate': 1, 'Runtime': 'container'}, 'Mode': {'Replicated': {'Replicas': 8}}, 'UpdateConfig': {'Parallelism': 1, 'FailureAction': 'pause', 'Monitor': 5000000000, 'MaxFailureRatio': 0, 'Order': 'stop-first'}, 'RollbackConfig': {'Parallelism': 1, 'FailureAction': 'pause', 'Monitor': 5000000000, 'MaxFailureRatio': 0, 'Order': 'stop-first'}, 'EndpointSpec': {'Mode': 'vip'}}, 'PreviousSpec': {'Name': 'mirror_nginx', 'Labels': {'com.docker.stack.image': 'nginx:stable-alpine', 'com.docker.stack.namespace': 'mirror', 'com.ouroboros.enable': 'true', 'traefik.backend': 'Mirror', 'traefik.docker.network': 'mirror', 'traefik.enable': 'true', 'traefik.frontend': 'Mirror', 'traefik.frontend.rule': 'Host:HOST', 'traefik.port': '80'}, 'TaskTemplate': {'ContainerSpec': {'Image': 'nginx:stable-alpine@sha256:b96aeeb1687703c49096f4969358d44f8520b671da94848309a3ba5be5b4c632', 'Labels': {'com.docker.stack.namespace': 'mirror'}, 'Privileges': {'CredentialSpec': None, 'SELinuxContext': None}, 'Mounts': [{'Type': 'bind', 'Source': '/opt/docker/mirror/nginx/nginx.conf', 'Target': '/etc/nginx/nginx.conf', 'ReadOnly': True}, {'Type': 'bind', 'Source': '/opt/mirror/', 'Target': '/var/www/vhosts/mirror', 'ReadOnly': True}], 'Isolation': 'default'}, 'Resources': {}, 'Placement': {'Platforms': [{'Architecture': 'amd64', 'OS': 'linux'}, {'OS': 'linux'}, {'Architecture': 'arm64', 'OS': 'linux'}, {'Architecture': '386', 'OS': 'linux'}, {'Architecture': 'ppc64le', 'OS': 'linux'}, {'Architecture': 's390x', 'OS': 'linux'}]}, 'Networks': [{'Target': 'j8ma50vt0chbvwjf3fvwfw6t7', 'Aliases': ['nginx']}], 'ForceUpdate': 1, 'Runtime': 'container'}, 'Mode': {'Replicated': {'Replicas': 8}}, 'EndpointSpec': {'Mode': 'vip'}}, 'Endpoint': {'Spec': {'Mode': 'vip'}, 'VirtualIPs': [{'NetworkID': 'j8ma50vt0chbvwjf3fvwfw6t7', 'Addr': '10.0.0.76/24'}]}, 'UpdateStatus': {'State': 'completed', 'StartedAt': '2019-02-07T09:16:18.486639368Z', 'CompletedAt': '2019-02-07T09:17:01.251909255Z', 'Message': 'update completed'}}
nginx:stable-alpine
nginx:stable-alpine
2019-02-13 17:19:43 : ERROR : base : Job "Run Once container update for unix://var/run/docker.sock (trigger: date[2019-02-13 17:19:43 CET], next run at: 2019-02-13 17:19:43 CET)" raised an exception
Traceback (most recent call last):
  File "/root/ouroboros/virtualenv/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/ouroboros/application/pyouroboros/dockerclient.py", line 438, in update
    sha256 = image_string.split('@')[1][7:]
IndexError: list index out of range```

I only removed all hostnames etc which are included in the trace.

**Comment by DirtyCajunRice** [comment] 2019-02-13 18:14
I cant seem to replicate your issue :/
```
>>> service.attrs['PreviousSpec']['TaskTemplate']['ContainerSpec']['Image']
'busybox:latest@sha256:7964ad52e396a6e045c39b5a44438424ac52e12e4d5a25d94895f2058cb863a0'
>>> service.attrs['Spec']['TaskTemplate']['ContainerSpec']['Image']
'busybox:glibc@sha256:d9fbf8e504f3fbdd6718621bcb21e98b962dd2621aab7b99890c639c5dffeb4e'
```
even when i do an update, the update still shows the spec with the sha. Im not sure what is going on in your environment. For now i can add a check/skip if there is no sha, because without the sha there is no other way to know what image it is using

**Comment by computeralex92** [comment] 2019-02-13 18:38
OK, that is strange:

I made a test with a another stack:
- Only the new stack: No error appears
- The new stack the old one: No error appears
- Only the old one: No error appears

I think the reason why now the old stack is working without any issue is that the containers where recreated when I disabled the label for ouroboros.

And Bingo; I think I found the "reason" for the issue:
I run for the old stack ouroboros without the dry mode; and this error appears:

```
2019-02-13 19:34:23 : ERROR : base : Job "Run Once container update for unix://var/run/docker.sock (trigger: date[2019-02-13 19:34:21 CET], next run at: 2019-02-13 19:34:21 CET)" raised an exception
Traceback (most recent call last):
  File "/root/ouroboros/virtualenv/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/ouroboros/application/pyouroboros/dockerclient.py", line 475, in update
    self.notification_manager.send(container_tuples=updated_service_tuples, socket=self.socket, kind='update')
  File "/root/ouroboros/application/pyouroboros/notifiers.py", line 57, in send
    ) for container, old_image, new_image in container_tuples
  File "/root/ouroboros/application/pyouroboros/notifiers.py", line 57, in <listcomp>
    ) for container, old_image, new_image in container_tuples
AttributeError: 'str' object has no attribute 'short_id'
```

And in dry mode again, our old error friend appears again:
```
2019-02-13 19:34:50 : ERROR : base : Job "Run Once container update for unix://var/run/docker.sock (trigger: date[2019-02-13 19:34:50 CET], next run at: 2019-02-13 19:34:50 CET)" raised an exception
Traceback (most recent call last):
  File "/root/ouroboros/virtualenv/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/ouroboros/application/pyouroboros/dockerclient.py", line 438, in update
    sha256 = image_string.split('@')[1][7:]
IndexError: list index out of range
```
So the first error while updating the service produce the second one.
Btw: the container will be recreated while the update failure.

**Comment by DirtyCajunRice** [comment] 2019-02-13 18:55
So you are saying the issue was transient of the other issue, and with the above fix it self resolved?

**Comment by DirtyCajunRice** [comment] 2019-02-13 19:00
i forgot to pin the fix for the notification manager. Its pinned as of the just now push

**Comment by computeralex92** [comment] 2019-02-13 20:48
> So you are saying the issue was transient of the other issue, and with the above fix it self resolved?

I think so, but the issue was solved with the recreation of the containers after the first update of the config.
It seems that the broken update process damage something which cause the issue when running the tool again.

**Comment by DirtyCajunRice** [comment] 2019-02-13 21:59
Sweet. Ok ill close this out as its being pushed to develop and then master tonight :) thanks for all your help!

**Closed by DirtyCajunRice** 2019-02-13 21:59 UTC
Labels: enhancement
