### ISSUE TITLE
docker-compose local and remote tls logger location

### ISSUE THREAD

**Issue by badsmoke** [pyouroboros/ouroboros#273] opened 2019-03-26 14:13 UTC
Hello,

how can i operate a local socket and several tcp dockers with it?
Can someone please tell me a configuration for docker-compose?

My scenario:
local docker that also runs ouroboros
10 remote docker with tls client verification

thank you

**Comment by DirtyCajunRice** [comment] 2019-03-26 15:01
please read the wiki, the above is explained in with verification and with how to address remote hosts

**Comment by badsmoke** [comment] 2019-03-27 06:48
hello thanks for the quick answer.

I've already read the wiki, but I still haven't figured out what the folder structure for the certificate should be like.


```
version: '3'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=debug
      - SELF_UPDATE=false
      - IGNORE=influxdb prometheus
      - TZ=Europe/Berlin
      - DATA_EXPORT=prometheus
      - PROMETHEUS_ADDR=0.0.0.0
      - PROMETHEUS_PORT=3579
      - LATEST=true
      - DOCKER_TLS=true
      - URL="unix://var/run/docker.sock tcp://remote-docker-1:2376  tcp://remote-docker-2:2376"
      - DOCKER_TLS_VERIFY=true
    ports:
      - 3579:3579
    restart: unless-stopped
    volumes:
      - /etc/docker/certs.d:/srv/docker_tls/
      - /var/run/docker.sock:/var/run/docker.sock
```
the folder /srv/docker_tls/ now contains the certificates

**Comment by dstidham617** [comment] 2019-03-27 15:44
I'm getting identical issues with remote hosts using tls but not verification

`Traceback (most recent call last):
  File "/usr/local/bin/ouroboros", line 5, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/ouroboros.py", line 153, in main
    docker = Docker(socket, config, data_manager, notification_manager)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 14, in __init__
    self.client = self.connect()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 35, in connect
    self.logger.error('%s is not a valid cert folder', cert_paths['cert_dir'])
AttributeError: 'Docker' object has no attribute 'logger'`

**Comment by DirtyCajunRice** [comment] 2019-04-09 03:01
The error is because we hadnt instanciated the logger when we connected. an oversight. That is being addressed. As for the error happening, it doesnt see the folders set as intended. for your edit2, verify is specifying a CA cert to verify against as per docker documentation. No cert specification at all will not work.

**Comment by badsmoke** [comment] 2019-04-18 11:45
are there any news on troubleshooting?

**Comment by DirtyCajunRice** [comment] 2019-04-25 01:04
logger moved. closing

**Closed by DirtyCajunRice** 2019-04-25 01:04 UTC
Labels: bug
