### ISSUE TITLE
Exception when trying update

### ISSUE THREAD

**Issue by yildiz-online** [pyouroboros/ouroboros#223] opened 2019-02-15 19:16 UTC
2019-02-15 19:59:05 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-02-15 20:03:38 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 275, in update
    updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 240, in socket_check
    if current_image.id != latest_image.id:
AttributeError: 'list' object has no attribute 'id'

Also experience a strange behavior, i noticed a lot of unexpected image downloaded and not cleaned, dunno if related.

**Comment by DirtyCajunRice** [comment] 2019-02-15 19:21
duplicate of #210 
please update to 1.2.1 and prune any old images :)

**Closed by DirtyCajunRice** 2019-02-15 19:21 UTC
Labels: duplicate

**Comment by yildiz-online** [comment] 2019-02-15 20:02
Updating manually worked fine:

2019-02-15 21:00:43 : INFO : ouroboros : Version: 1.2.1-master
2019-02-15 21:01:13 : INFO : dockerclient : ActiveMQ will be updated

Thank you very much
